version: '1'

services: 
    # node api service
    api: 
        build: . 
        ports: 
         - 8080:8080
        volumes:
            - .:/usr/src/app
        environment: 
            PORT: 3000
            MONGO_URI: mongodb://mongo_db:27017
            DB_NAME: helsinki_bikes
            NAME: TrulyMittal
        depends_on:
         - mongo_db 
# mongo service
    mongo_db:
        container_name: db_container
        image: mongo:latest
        restart: always
        ports:
            - 2717:27017
        volumes:
        - mongo_db:/data/db  

volumes: 
    mongo_db: {}