version: '3.8'

services:
  # mongodb service
  mongo_db:
  # container name is optional
    container_name: citybikes
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  # node api service
  api: 
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DBNAME: citybikes
      NAME: linhnguyen
    depends_on:
      - mongo_db
  
volumes:
  mongo_db: {}