version: '3.8'

services:
  # mongodb service
  mongo_db:
    container_name: citybikes
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  # node api service
  api: 
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb-server/helsinki-bike-frontend
      DBNAME: citybikes
      NAME: linhnguyen
    depends_on:
      - mongo_db
  
volumes:
  mongo_db: {}